export enum RegisterFrequencyStep {
  SHOW_QR_CODE_TIPS,
  SHOW_SESSION_CODE_TIPS,
  CHECK_CAMERA_PERMISSION,
  READ_QR_CODE,
  CHECKING_CODE,
  CHECK_GPS_PERMISSION,
  GET_POSITION,
  GENERIC_ERROR,
  GPS_ERROR,
  SUCCESS,
  READ_SESSION_CODE,
  CHECK_SESSION_CODE,
}
